version: '3'

services:

  rest_api:
    image: docker.io/hakeberplus4/docker-stack-rest
    ports:
      - "9080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    deploy:
      replicas: 2
      placement:
        constraints:
        - node.role == manager
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 1G
